In [1]:

#   ____        _           ____ _                  _             
#  |  _ \  __ _| |_ __ _   / ___| | ___  __ _ _ __ (_)_ __   __ _ 
#  | | | |/ _` | __/ _` | | |   | |/ _ \/ _` | '_ \| | '_ \ / _` |
#  | |_| | (_| | || (_| | | |___| |  __/ (_| | | | | | | | | (_| |
#  |____/ \__,_|\__\__,_|  \____|_|\___|\__,_|_| |_|_|_| |_|\__, |
#                                                           |___/ 

# AUTHORS : Gianna Galard, George Melek, and Austin Li
# CSC412 PROFESSOR IMBERMAN
# DATE : 11/23/2021
import pandas as pd 
import numpy as np
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [2]:
# load the heart data
#df = pd.read_csv('\\Users\\gianna\\Desktop\\Data-Cleaning\\heartdata.csv') 
#df = pd.read_csv('/Users/george/Desktop/CSC-412-Group-Project/Data-Cleaning/heartdata.csv')
df = pd.read_csv('/Users/george/Downloads/processed.cleveland.data', header=None)

In [3]:
# print the first 5 rows of the data set
df.head()

0    1    2      3      4    5    6      7    8    9    10   11   12  13
0  63.0  1.0  1.0  145.0  233.0  1.0  2.0  150.0  0.0  2.3  3.0  0.0  6.0   0
1  67.0  1.0  4.0  160.0  286.0  0.0  2.0  108.0  1.0  1.5  2.0  3.0  3.0   2
2  67.0  1.0  4.0  120.0  229.0  0.0  2.0  129.0  1.0  2.6  2.0  2.0  7.0   1
3  37.0  1.0  3.0  130.0  250.0  0.0  0.0  187.0  0.0  3.5  3.0  0.0  3.0   0
4  41.0  0.0  2.0  130.0  204.0  0.0  2.0  172.0  0.0  1.4  1.0  0.0  3.0   0

In [4]:
df.columns = ['age',
 'sex',
 'cp',
 'restbp',
 'chol',
 'fbs',
 'restecg',
 'thalach',
 'exang',
 'oldpeak',
 'slope',
 'ca',
 'thal',
 'hd']

In [5]:
# determine the datatype of each column
df.dtypes

age        float64
sex        float64
cp         float64
restbp     float64
chol       float64
fbs        float64
restecg    float64
thalach    float64
exang      float64
oldpeak    float64
slope      float64
ca          object
thal        object
hd           int64
dtype: object

In [6]:
# print the unique values for the columns **ca** and **thal**
print(df.ca.unique()) 
print(df.thal.unique())

['0.0' '3.0' '2.0' '1.0' '?']
['6.0' '3.0' '7.0' '?']


In [7]:
# determine how many rows contain missing values in the columns **ca** and **thal**
#print(df.ca.isnull().sum()) 
#print(df.thal.isnull().sum()) 

In [8]:
# determine how many rows contain missing values, the python code is below
len(df.loc[(df['ca'] == '?') | (df['thal'] == '?')]) 

6

In [9]:
# since only 6 rows have missing values, let's look at them
missing = df.loc[(df['ca'] == '?') | (df['thal'] == '?')]
missing

age  sex   cp  restbp   chol  fbs  restecg  thalach  exang  oldpeak  \
87   53.0  0.0  3.0   128.0  216.0  0.0      2.0    115.0    0.0      0.0   
166  52.0  1.0  3.0   138.0  223.0  0.0      0.0    169.0    0.0      0.0   
192  43.0  1.0  4.0   132.0  247.0  1.0      2.0    143.0    1.0      0.1   
266  52.0  1.0  4.0   128.0  204.0  1.0      0.0    156.0    1.0      1.0   
287  58.0  1.0  2.0   125.0  220.0  0.0      0.0    144.0    0.0      0.4   
302  38.0  1.0  3.0   138.0  175.0  0.0      0.0    173.0    0.0      0.0   

     slope   ca thal  hd  
87     1.0  0.0    ?   0  
166    1.0    ?  3.0   0  
192    2.0    ?  7.0   1  
266    2.0  0.0    ?   2  
287    2.0    ?  7.0   0  
302    1.0    ?  3.0   0

In [10]:
# 10 - count the number of rows in the full dataset
len(df)

303

In [11]:
# remove the rows with missing values
df.drop(missing.index, inplace=True) 

In [12]:
# verify that the rows with missing values have been removed
len(df) # the length of the dataframe should be reduced by 6 rows

297

In [13]:
# verify using the unique function that "ca" and "thal" do not have missing values
print(df.ca.unique())
print(df.thal.unique())

['0.0' '3.0' '2.0' '1.0']
['6.0' '3.0' '7.0']


In [14]:
# split the data into dependent and independent variables
# the column of data that we will to to make classifications
#X = df.iloc[:,:-1] # this line of code is the same as X = df.drop(['hd'], axis=1)
X = df.copy()
X.drop(['hd'], axis=1, inplace=True)
# the column of data that we want to predict
y = df.copy()
y = y['hd']
#y = df.iloc[:,-1] # this line of code is the same as y = df['hd']

In [15]:
# print the head of both the X and y dataframes so that you can verify this worked correctly
X.head() # this is the independent variables

age  sex   cp  restbp   chol  fbs  restecg  thalach  exang  oldpeak  \
0  63.0  1.0  1.0   145.0  233.0  1.0      2.0    150.0    0.0      2.3   
1  67.0  1.0  4.0   160.0  286.0  0.0      2.0    108.0    1.0      1.5   
2  67.0  1.0  4.0   120.0  229.0  0.0      2.0    129.0    1.0      2.6   
3  37.0  1.0  3.0   130.0  250.0  0.0      0.0    187.0    0.0      3.5   
4  41.0  0.0  2.0   130.0  204.0  0.0      2.0    172.0    0.0      1.4   

   slope   ca thal  
0    3.0  0.0  6.0  
1    2.0  3.0  3.0  
2    2.0  2.0  7.0  
3    3.0  0.0  3.0  
4    1.0  0.0  3.0

In [16]:
y.head() # this is the dependent variables

0    0
1    2
2    1
3    0
4    0
Name: hd, dtype: int64

In [17]:
X['restecg'].unique()

array([2., 0., 1.])

In [18]:
X_encoded = pd.get_dummies(X, columns=['cp',
 'restecg',
'slope',
 'thal'])

In [19]:
X_encoded.head()

age  sex  restbp   chol  fbs  thalach  exang  oldpeak   ca  cp_1.0  ...  \
0  63.0  1.0   145.0  233.0  1.0    150.0    0.0      2.3  0.0       1  ...   
1  67.0  1.0   160.0  286.0  0.0    108.0    1.0      1.5  3.0       0  ...   
2  67.0  1.0   120.0  229.0  0.0    129.0    1.0      2.6  2.0       0  ...   
3  37.0  1.0   130.0  250.0  0.0    187.0    0.0      3.5  0.0       0  ...   
4  41.0  0.0   130.0  204.0  0.0    172.0    0.0      1.4  0.0       0  ...   

   cp_4.0  restecg_0.0  restecg_1.0  restecg_2.0  slope_1.0  slope_2.0  \
0       0            0            0            1          0          0   
1       1            0            0            1          0          1   
2       1            0            0            1          0          1   
3       0            1            0            0          0          0   
4       0            0            0            1          1          0   

   slope_3.0  thal_3.0  thal_6.0  thal_7.0  
0          1         0         1         0  
1          0         1         0         0  
2          0         0         0         1  
3          1         1         0         0  
4          0         1         0         0  

[5 rows x 22 columns]

In [20]:
y.unique() # this should return the unique values in the dependent variable

array([0, 2, 1, 3, 4])

In [21]:
y_not_zero_idx = y > 0 # this is a boolean array that is true if the dependent variable is greater than 0
y[y_not_zero_idx] = 1 # this changes the dependent variable to 1 if it is greater than 0
y.unique()

array([0, 1])

In [22]:
# split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X_encoded, y, test_size=0.2, random_state=0) 

In [23]:
# use this data to run a decision tree on the data
tree = DecisionTreeClassifier(max_depth=None, random_state=0) # create a decision tree classifier
tree.fit(X_train, y_train) # fit the data to the tree
y_pred = tree.predict(X_test) # this is the actual prediction

In [24]:
# print how many levels of the tree were created and the accuracy of the model
print(tree.tree_.max_depth) # this is the number of levels in the tree
print(accuracy_score(y_test, y_pred)) # this is the accuracy of the model

8
0.75
